swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /personas/:
    put:
      tags:
      - personas
      description: Actualizar datos de persona
      operationId: TerceroController.ActualizarPersona
      parameters:
      - in: body
        name: body
        description: body for Actualizar datos de persona content
        required: true
        schema:
          $ref: '#/definitions/{}'
      responses:
        "200":
          description: '{}'
        "403":
          description: body is empty
    post:
      tags:
      - personas
      description: Guardar Persona
      operationId: TerceroController.PostPersona
      parameters:
      - in: body
        name: body
        description: body for Guardar Persona content
        required: true
        schema:
          $ref: '#/definitions/{}'
      responses:
        "201":
          description: '{int}'
        "400":
          description: the request contains incorrect syntax
  /personas/{tercero_id}:
    get:
      tags:
      - personas
      description: get ConsultaPersona by id
      operationId: TerceroController.ConsultarPersona
      parameters:
      - in: path
        name: tercero_id
        description: Id del tercero
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: '{}'
        "404":
          description: not found resource
  /personas/{tercero_id}/complementarios:
    get:
      tags:
      - personas
      description: get ConsultarDatosComplementarios by id
      operationId: TerceroController.ConsultarDatosComplementarios
      parameters:
      - in: path
        name: tercero_id
        description: Id del ente
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: '{}'
        "404":
          description: not found resource
  /personas/{tercero_id}/contacto:
    get:
      tags:
      - personas
      description: get ConsultarDatosContacto by id
      operationId: TerceroController.ConsultarDatosContacto
      parameters:
      - in: path
        name: tercero_id
        description: Id del Tercero
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: '{}'
        "404":
          description: not found resource
  /personas/{tercero_id}/familiar:
    get:
      tags:
      - personas
      description: get ConsultarDatosFamiliar by id
      operationId: TerceroController.ConsultarDatosFamiliar
      parameters:
      - in: path
        name: tercero_id
        description: Id del Tercero
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: '{}'
        "404":
          description: not found resource
  /personas/{tercero_id}/formacion-pregrado:
    get:
      tags:
      - personas
      description: get ConsultarDatosFormacionPregrado by id
      operationId: TerceroController.ConsultarDatosFormacionPregrado
      parameters:
      - in: path
        name: tercero_id
        description: Id del Tercero
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: '{}'
        "404":
          description: not found resource
  /personas/{tercero_id}/info-solicitante:
    get:
      tags:
      - personas
      description: get ConsultarInfoSolicitante by id
      operationId: TerceroController.ConsultarInfoSolicitante
      parameters:
      - in: path
        name: tercero_id
        description: Id del tercero
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: '{}'
        "404":
          description: not found resource
  /personas/autores:
    post:
      tags:
      - personas
      description: Guardar autor
      operationId: TerceroController.PostAutor
      parameters:
      - in: body
        name: body
        description: body for Guardar autor content
        required: true
        schema:
          $ref: '#/definitions/{}'
      responses:
        "201":
          description: '{int}'
        "400":
          description: the request contains incorrect syntax
  /personas/complementarios:
    put:
      tags:
      - personas
      description: ActualizarDatosComplementarios
      operationId: TerceroController.ActualizarDatosComplementarios
      parameters:
      - in: body
        name: body
        description: body for Actualizar los datos complementarios content
        required: true
        schema:
          $ref: '#/definitions/{}'
      responses:
        "200":
          description: '{}'
        "403":
          description: body is empty
    post:
      tags:
      - personas
      description: Guardar Datos Complementarios Persona
      operationId: TerceroController.GuardarDatosComplementarios
      parameters:
      - in: body
        name: body
        description: body for Guardar Datos Complementarios Persona content
        required: true
        schema:
          $ref: '#/definitions/{}'
      responses:
        "201":
          description: '{int}'
        "400":
          description: the request contains incorrect syntax
  /personas/complementarios-par-academico:
    post:
      tags:
      - personas
      description: Guardar Datos Complementarios Persona ParAcademico
      operationId: TerceroController.GuardarDatosComplementariosParAcademico
      parameters:
      - in: body
        name: body
        description: body for Guardar Datos Complementarios Persona content
        required: true
        schema:
          $ref: '#/definitions/{}'
      responses:
        "201":
          description: '{int}'
        "400":
          description: the request contains incorrect syntax
  /personas/contacto:
    post:
      tags:
      - personas
      description: Guardar DatosContacto
      operationId: TerceroController.PostrDatosContacto
      parameters:
      - in: body
        name: body
        description: body for Guardar DatosContacto content
        required: true
        schema:
          $ref: '#/definitions/{}'
      responses:
        "201":
          description: '{int}'
        "400":
          description: the request contains incorrect syntax
  /personas/existencia/{numeroDocumento}:
    get:
      tags:
      - personas
      description: get ConsultarExistenciaPersona by NumeroIdentificacion
      operationId: TerceroController.ConsultarExistenciaPersona
      parameters:
      - in: path
        name: numeroDocumento
        description: numero documento del tercero
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: '{}'
        "404":
          description: not found resource
  /personas/info-familiar:
    put:
      tags:
      - personas
      description: Actualiza la informacion familiar del tercero
      operationId: TerceroController.ActualizarInfoFamiliar
      parameters:
      - in: body
        name: body
        description: body for Actualizar la info familiar del tercero content
        required: true
        schema:
          $ref: '#/definitions/{}'
      responses:
        "200":
          description: '{}'
        "403":
          description: body is empty
  /personas/nit:
    get:
      tags:
      - personas
      description: Retorna una lista de terceros con su NIT y nombre completo.
      operationId: TerceroController.ObtenerTerceroConNIT
      responses:
        "200":
          description: '"Lista de terceros con NIT, nombre completo y label correspondiente."'
          schema:
            type: array
            items:
              $ref: '#/definitions/TerceroConNIT'
        "400":
          description: '"bad request" en caso de una solicitud incorrecta o problemas en la consulta.'
definitions:
  '{}':
    title: '{}'
    type: object
  TerceroConNIT:
    title: TerceroConNIT
    type: object
tags:
- name: personas
  description: |
    TerceroController operations for Tercero
