swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /persona/:
    put:
      tags:
      - persona
      description: Actualizar datos de persona
      operationId: TerceroController.ActualizarPersona
      parameters:
      - in: body
        name: body
        description: body for Actualizar datos de persona content
        required: true
        schema:
          $ref: '#/definitions/{}'
      responses:
        "200":
          description: '{}'
        "403":
          description: body is empty
    post:
      tags:
      - persona
      description: Guardar Persona
      operationId: TerceroController.PostPersona
      parameters:
      - in: body
        name: body
        description: body for Guardar Persona content
        required: true
        schema:
          $ref: '#/definitions/{}'
      responses:
        "201":
          description: '{int}'
        "400":
          description: the request contains incorrect syntax
  /persona/{tercero_id}:
    get:
      tags:
      - persona
      description: get ConsultaPersona by id
      operationId: TerceroController.ConsultarPersona
      parameters:
      - in: path
        name: tercero_id
        description: Id del tercero
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: '{}'
        "404":
          description: not found resource
  /persona/{tercero_id}/complementarios:
    get:
      tags:
      - persona
      description: get ConsultarDatosComplementarios by id
      operationId: TerceroController.ConsultarDatosComplementarios
      parameters:
      - in: path
        name: tercero_id
        description: Id del ente
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: '{}'
        "404":
          description: not found resource
  /persona/{tercero_id}/contacto:
    get:
      tags:
      - persona
      description: get ConsultarDatosContacto by id
      operationId: TerceroController.ConsultarDatosContacto
      parameters:
      - in: path
        name: tercero_id
        description: Id del Tercero
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: '{}'
        "404":
          description: not found resource
  /persona/{tercero_id}/familiar:
    get:
      tags:
      - persona
      description: get ConsultarDatosFamiliar by id
      operationId: TerceroController.ConsultarDatosFamiliar
      parameters:
      - in: path
        name: tercero_id
        description: Id del Tercero
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: '{}'
        "404":
          description: not found resource
  /persona/{tercero_id}/formacion-pregrado:
    get:
      tags:
      - persona
      description: get ConsultarDatosFormacionPregrado by id
      operationId: TerceroController.ConsultarDatosFormacionPregrado
      parameters:
      - in: path
        name: tercero_id
        description: Id del Tercero
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: '{}'
        "404":
          description: not found resource
  /persona/{tercero_id}/info-solicitante:
    get:
      tags:
      - persona
      description: get ConsultarInfoSolicitante by id
      operationId: TerceroController.ConsultarInfoSolicitante
      parameters:
      - in: path
        name: tercero_id
        description: Id del tercero
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: '{}'
        "404":
          description: not found resource
  /persona/autores:
    post:
      tags:
      - persona
      description: Guardar autor
      operationId: TerceroController.PostAutor
      parameters:
      - in: body
        name: body
        description: body for Guardar autor content
        required: true
        schema:
          $ref: '#/definitions/{}'
      responses:
        "201":
          description: '{int}'
        "400":
          description: the request contains incorrect syntax
  /persona/complementarios:
    put:
      tags:
      - persona
      description: ActualizarDatosComplementarios
      operationId: TerceroController.ActualizarDatosComplementarios
      parameters:
      - in: body
        name: body
        description: body for Actualizar los datos complementarios content
        required: true
        schema:
          $ref: '#/definitions/{}'
      responses:
        "200":
          description: '{}'
        "403":
          description: body is empty
    post:
      tags:
      - persona
      description: Guardar Datos Complementarios Persona
      operationId: TerceroController.GuardarDatosComplementarios
      parameters:
      - in: body
        name: body
        description: body for Guardar Datos Complementarios Persona content
        required: true
        schema:
          $ref: '#/definitions/{}'
      responses:
        "201":
          description: '{int}'
        "400":
          description: the request contains incorrect syntax
  /persona/complementarios-par:
    post:
      tags:
      - persona
      description: Guardar Datos Complementarios Persona ParAcademico
      operationId: TerceroController.GuardarDatosComplementariosParAcademico
      parameters:
      - in: body
        name: body
        description: body for Guardar Datos Complementarios Persona content
        required: true
        schema:
          $ref: '#/definitions/{}'
      responses:
        "201":
          description: '{int}'
        "400":
          description: the request contains incorrect syntax
  /persona/contacto:
    post:
      tags:
      - persona
      description: Guardar DatosContacto
      operationId: TerceroController.PostrDatosContacto
      parameters:
      - in: body
        name: body
        description: body for Guardar DatosContacto content
        required: true
        schema:
          $ref: '#/definitions/{}'
      responses:
        "201":
          description: '{int}'
        "400":
          description: the request contains incorrect syntax
  /persona/existencia/{numeroDocumento}:
    get:
      tags:
      - persona
      description: get ConsultarExistenciaPersona by NumeroIdentificacion
      operationId: TerceroController.ConsultarExistenciaPersona
      parameters:
      - in: path
        name: numeroDocumento
        description: numero documento del tercero
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: '{}'
        "404":
          description: not found resource
  /persona/info-familiar:
    put:
      tags:
      - persona
      description: Actualiza la informacion familiar del tercero
      operationId: TerceroController.ActualizarInfoFamiliar
      parameters:
      - in: body
        name: body
        description: body for Actualizar la info familiar del tercero content
        required: true
        schema:
          $ref: '#/definitions/{}'
      responses:
        "200":
          description: '{}'
        "403":
          description: body is empty
definitions:
  '{}':
    title: '{}'
    type: object
tags:
- name: persona
  description: |
    TerceroController operations for Tercero
