appname = sga_tercero_mid
# httpport = ${SGA_TERCERO_MID_HTTP_PORT}
httpport = 8181
runmode = dev
autorender = false
copyrequestbody = true
EnableDocs = true
sqlconn = 

# logPath= ${SGA_MID_LOG}

# InscripcionService = ${INSCRIPCION_SERVICE}
# ProyectoAcademicoService= ${PROYECTO_SERVICE}
# TercerosService= ${TERCEROS_SERVICE}
# UbicacionesService= ${UBICACIONES_SERVICE}

InscripcionService = pruebasapi2.intranetoas.udistrital.edu.co:8208/v1/
ProyectoAcademicoService= pruebasapi.intranetoas.udistrital.edu.co:8116/v1/
TercerosService= pruebasapi.intranetoas.udistrital.edu.co:8121/v1/
UbicacionesService= pruebasapi2.intranetoas.udistrital.edu.co:8085/v1/


